name: test1
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: usertest
        uses: actions/checkout@v1
      
      - name: test_dayo
        run: |
          cat test.txt
          echo "1">>test.txt
